### PR TITLE
Website & Setup Guide

### PR DESCRIPTION
**Pull request by aklingspor**
I setup a website at http://yeezycopper.com/ that's run by GitHub Pages, and wrote up a setup guide for those that need a bit of help figuring this out.

Added some stupid kanye GIFs too for fun.

Cheers

### CODE REVIEW

**Comment by mannynotfound** [comment]
this is amazing. omg. I cant believe youve done this.

**Comment by mannynotfound** [comment]
@aklingspor im going to update the README to be a little more like original + include the great work you did. Thanks so much! Good luck!!!

**Comment by aklingspor** [comment]
@mannynotfound thank you so much!! haha perfect, and good luck on your future projects!

**Comment by aklingspor** [comment]
@mannynotfound haha i'm sorry i didn't add any actual code to the project, but i hope i helped make this look like a publishable thing. i'm kinda new to this stuff, and i'm 16 lol. thanks again for letting me play with your code!

**Pull request merged**
